# Generated by Django 4.2.3 on 2023-07-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hithi', '0003_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create',
            new_name='created_at',
        ),
    ]
